name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Build go library
        run: |
          go build -buildmode=c-archive -o python/libtailscale.a github.com/tailscale/libtailscale

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        with:
          package-dir: python
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
